spring.application.name=car-catalog-api
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
management.endpoints.web.exposure.include=health,info
app.cors.allowed-origin=http://localhost:4200
